#pragma once
#include "gv_base_type.h"
#include "gv_base_api.h"
#include "gvt_value.h"
#include "gv_base_functor.h"
#include "gv_base_class.h"
#include "gv_singleton.h"
#include "gv_base_policy.h"
#include "gv_base_visitor.h"
