// data type string

GVM_MAKE_ID(byte)
GVM_MAKE_ID(char)
GVM_MAKE_ID(short)
GVM_MAKE_ID(ushort)
GVM_MAKE_ID(int)
GVM_MAKE_ID(uint)
GVM_MAKE_ID(long)
GVM_MAKE_ID(ulong)
GVM_MAKE_ID(float)
GVM_MAKE_ID(double)
GVM_MAKE_ID(string)
GVM_MAKE_ID(id)
GVM_MAKE_ID(ptr)
GVM_MAKE_ID(ref_ptr)
GVM_MAKE_ID(vector3)
GVM_MAKE_ID(matrix44)
GVM_MAKE_ID(object)
GVM_MAKE_ID(array)
GVM_MAKE_ID(static_array)

// common id
GVM_MAKE_ID(xml)
GVM_MAKE_ID(binary)
GVM_MAKE_ID(main)
GVM_MAKE_ID(base)
GVM_MAKE_ID(native)
GVM_MAKE_ID(script)
GVM_MAKE_ID(vector)
GVM_MAKE_ID(ai)
GVM_MAKE_ID(net)
GVM_MAKE_ID(render)
GVM_MAKE_ID(network)
GVM_MAKE_ID(memory)
GVM_MAKE_ID(physic)
GVM_MAKE_ID(console)
GVM_MAKE_ID(ui)
GVM_MAKE_ID(max)
GVM_MAKE_ID(min)
GVM_MAKE_ID(null)
GVM_MAKE_ID(new)
GVM_MAKE_ID(delete)
GVM_MAKE_ID(unknown)
GVM_MAKE_ID(any)
GVM_MAKE_ID(none)
GVM_MAKE_ID(dummy)
GVM_MAKE_ID(read)
GVM_MAKE_ID(write)
GVM_MAKE_ID(event)
GVM_MAKE_ID(floor)
GVM_MAKE_ID(ceiling)
GVM_MAKE_ID(front)
GVM_MAKE_ID(back)
GVM_MAKE_ID(left)
GVM_MAKE_ID(right);

GVM_MAKE_ID(info)
GVM_MAKE_ID(error)
GVM_MAKE_ID(warning)
GVM_MAKE_ID(debug)
GVM_MAKE_ID(database)

// some module name
GVM_MAKE_ID(framework)
GVM_MAKE_ID(android)
GVM_MAKE_ID(ios)
GVM_MAKE_ID(pc)
GVM_MAKE_ID(gp3d)
GVM_MAKE_ID(dx)
GVM_MAKE_ID(opengl)

// thread names
GVM_MAKE_ID(async_log_thread)

// network id
GVM_MAKE_ID(server)
GVM_MAKE_ID(client)
GVM_MAKE_ID(client_0)
GVM_MAKE_ID(client_1)
GVM_MAKE_ID(client_2)
GVM_MAKE_ID(client_3)
GVM_MAKE_ID(socket)
GVM_MAKE_ID(server_udp_iocp)
GVM_MAKE_ID(server_udp_iocp_worker)
GVM_MAKE_ID(server_udp_iocp_worker_0)
GVM_MAKE_ID(server_udp_iocp_worker_1)
GVM_MAKE_ID(server_udp_iocp_worker_2)
GVM_MAKE_ID(server_udp_iocp_worker_3)
GVM_MAKE_ID(server_udp_iocp_APC)

// data value
GVM_MAKE_ID(zero)
GVM_MAKE_ID(one)
GVM_MAKE_ID(two)
GVM_MAKE_ID(three)
GVM_MAKE_ID(four)
GVM_MAKE_ID(five)
GVM_MAKE_ID(six)
GVM_MAKE_ID(seven)
GVM_MAKE_ID(eight)
GVM_MAKE_ID(nine)
GVM_MAKE_ID(ten)

//
GVM_MAKE_ID(circle)
GVM_MAKE_ID(up)
GVM_MAKE_ID(down)
