//
//=========================basic=========================
REG_UNIT_TEST(unit_test_array_simple)
REG_UNIT_TEST(unit_test_string_simple)
REG_UNIT_TEST(unit_test_ring_buf_simple)
REG_UNIT_TEST(unit_test_array_static)
REG_UNIT_TEST(unit_test_stack)
REG_UNIT_TEST(unit_test_slist)
REG_UNIT_TEST(unit_test_boost_range_test)
REG_UNIT_TEST(unit_test_hash_map_simple)
REG_UNIT_TEST(unit_test_memory_cached)
// REG_UNIT_TEST(unit_test_gvt_memory_pool)
REG_UNIT_TEST(unit_test_gvt_singleton)
REG_UNIT_TEST(unit_test_call_stack)
REG_UNIT_TEST(unit_test_string_to_float_to_int_conversion)
REG_UNIT_TEST(unit_test_file_manager)
REG_UNIT_TEST(unit_test_lexer)
// REG_UNIT_TEST(unit_test_boost_time)
// REG_UNIT_TEST(unit_test_gv_memory_pool)
REG_UNIT_TEST(unit_test_gvt_set)
REG_UNIT_TEST(unit_test_gv_xml_parser)
REG_UNIT_TEST(unit_test_array_cached)
REG_UNIT_TEST(unit_test_dlist)
REG_UNIT_TEST(unit_test_gv_id)
REG_UNIT_TEST(unit_test_thread_simple)
REG_UNIT_TEST(unit_test_profiler_simple)
REG_UNIT_TEST(unit_test_log)
REG_UNIT_TEST(unit_test_ref_count)
REG_UNIT_TEST(unit_test_pool_fixed_size)
// REG_UNIT_TEST(unit_test_read_write_lock)
REG_UNIT_TEST(unit_test_lock_free_list)
REG_UNIT_TEST(unit_test_lock_free_list_function)
REG_UNIT_TEST(unit_test_console_event)
REG_UNIT_TEST(unit_test_gv_memory_stack)
REG_UNIT_TEST(unit_test_lock_free_pool)
REG_UNIT_TEST(unit_test_dictionary)
REG_UNIT_TEST(unit_test_stats)

//=========================math=========================
REG_UNIT_TEST(unit_test_vector_generic)
REG_UNIT_TEST(unit_test_matrix_generic)
REG_UNIT_TEST(unit_test_vector3)
REG_UNIT_TEST(unit_test_matrix43)
REG_UNIT_TEST(unit_test_matrix44)
REG_UNIT_TEST(unit_test_quaternion)
REG_UNIT_TEST(unit_test_euler)
REG_UNIT_TEST(unit_test_axis_angle)
REG_UNIT_TEST(unit_test_color)
// REG_UNIT_TEST(unit_test_matrix44_xna)
REG_UNIT_TEST(unit_test_dynamic_vector)
REG_UNIT_TEST(unit_test_geom)
REG_UNIT_TEST(unit_test_filter)
REG_UNIT_TEST(unit_test_fixed)
REG_UNIT_TEST(unit_test_trace_line_2d)

//
//=========================network=========================
REG_UNIT_TEST(unit_test_network_address)
REG_UNIT_TEST(unit_test_network_1v1_tcp_server)
REG_UNIT_TEST(unit_test_network_packet)
REG_UNIT_TEST(unit_test_rudp_server)
REG_UNIT_TEST(unit_test_network_1v1_udp_server)
#if defined(WIN32)
REG_UNIT_TEST(unit_test_iocp_udp_server)
#if GV_WITH_DATABASE
REG_UNIT_TEST(unit_test_data_base)
REG_UNIT_TEST(unit_test_database_stored_proc)
#endif
#endif
REG_UNIT_TEST(unit_test_asio)
REG_UNIT_TEST(unit_test_asio_chat)
//SN_TODO to fix the udp aiso sample
//REG_UNIT_TEST(unit_test_asio_udp)

//
//=========================tools=========================
REG_UNIT_TEST(tool_trace_parser)
REG_UNIT_TEST(tool_make_gv_file)
REG_UNIT_TEST(tool_lua_console)
REG_UNIT_TEST(tool_parser_xml_dom)
REG_UNIT_TEST(tool_memory_alloc_analysis)
REG_UNIT_TEST(tool_remove_duplicate)
REG_UNIT_TEST(tool_find_duplicate_asset)
REG_UNIT_TEST(tool_c_to_cpp)
REG_UNIT_TEST(tool_bp_to_cpp)
REG_UNIT_TEST(tool_file_visitor)
