#include "stdafx.h"
#include "gv_base.h"

using namespace gv;
using namespace std;

#include "unit_test_array_simple.hpp"
#include "unit_test_string_simple.hpp"
#include "unit_test_ring_buf_simple.hpp"
#include "unit_test_array_static.hpp"
#include "unit_test_stack.hpp"
#include "unit_test_slist.hpp"
#include "unit_test_boost_range_test.hpp"
#include "unit_test_hash_map_simple.hpp"
#include "unit_test_memory_cached.hpp"
//#include "unit_test_gvt_memory_pool.hpp"
#include "unit_test_gvt_singleton.hpp"
#include "unit_test_call_stack.hpp"
#include "unit_test_string_to_float_to_int_conversion.hpp"
#include "unit_test_file_manager.hpp"
#include "unit_test_lexer.hpp"
//#include "unit_test_boost_time.hpp"
//#include "unit_test_gv_memory_pool.hpp"
#include "unit_test_gvt_set.hpp"
#include "unit_test_gv_xml_parser.hpp"
#include "unit_test_array_cached.hpp"
#include "unit_test_dlist.hpp"
#include "unit_test_gv_id.hpp"
#include "unit_test_thread_simple.hpp"
#include "unit_test_profiler_simple.hpp"
#include "unit_test_log.hpp"
#include "unit_test_ref_count.hpp"
//#include "unit_test_lock_free_double_buffer.hpp"
#include "unit_test_pool_fixed_size.hpp"
//#include "unit_test_lock_free_double_buffer_resizeable.hpp"
//#include "unit_test_geom.hpp"
//#include "unit_test_filter.hpp"
//#include "unit_test_read_write_lock.hpp"
#include "unit_test_lock_free_list.hpp"
#include "unit_test_lock_free_list_function.hpp"
#include "unit_test_console_event.hpp"
#include "unit_test_gv_memory_stack.hpp"
#include "unit_test_lock_free_pool.hpp"
#include "unit_test_dictionary.hpp"
#include "unit_test_stats.hpp"
//#include "unit_test_trace_line_2d.hpp"
