GVM_MAKE_ID(gv_module)
GVM_MAKE_ID(gv_object)
GVM_MAKE_ID(gv_var_info)
GVM_MAKE_ID(gv_func_info)
GVM_MAKE_ID(gv_com_x_mesh_renderer)
GVM_MAKE_ID(terrain)
GVM_MAKE_ID(player)
GVM_MAKE_ID(creature)
GVM_MAKE_ID(name)

// bone structure
GVM_MAKE_ID(root)
GVM_MAKE_ID(engine)
GVM_MAKE_ID(account)
GVM_MAKE_ID(characters)

GVM_MAKE_ID(diffuse)
GVM_MAKE_ID(gloss)
GVM_MAKE_ID(specular)
GVM_MAKE_ID(sky)
GVM_MAKE_ID(color)
GVM_MAKE_ID(depth)

// material
GVM_MAKE_ID(g_Diffuse)
GVM_MAKE_ID(g_Specular)
GVM_MAKE_ID(g_Ambient)
GVM_MAKE_ID(g_SunDir)

GVM_MAKE_ID(g_TexBase)
GVM_MAKE_ID(g_TexNormal)
GVM_MAKE_ID(g_TexEnv)
GVM_MAKE_ID(g_TexGloss)
GVM_MAKE_ID(g_TexLightmap)
GVM_MAKE_ID(g_TexSpecular)
GVM_MAKE_ID(g_TexNormalHeight)

GVM_MAKE_ID(MtxLocalWorld)
GVM_MAKE_ID(MtxLocalView)
GVM_MAKE_ID(MtxProjection)

GVM_MAKE_ID(g_color_buffer)
GVM_MAKE_ID(g_depth_buffer)
GVM_MAKE_ID(g_normal_buffer)

GVM_MAKE_ID(FX)
GVM_MAKE_ID(POSITION)
GVM_MAKE_ID(POSITION0)
GVM_MAKE_ID(POSITION1)
GVM_MAKE_ID(POSITION2)

GVM_MAKE_ID(NORMAL)
GVM_MAKE_ID(NORMAL0)

GVM_MAKE_ID(BLENDWEIGHT)
GVM_MAKE_ID(BLENDWEIGHT0)
GVM_MAKE_ID(BLENDWEIGHT1)

GVM_MAKE_ID(BLENDINDICES)
GVM_MAKE_ID(BLENDINDICES0)
GVM_MAKE_ID(BLENDINDICES1)

GVM_MAKE_ID(PSIZE)
GVM_MAKE_ID(PSIZE0)
GVM_MAKE_ID(PSIZE1)

GVM_MAKE_ID(COLOR)
GVM_MAKE_ID(COLOR0)
GVM_MAKE_ID(COLOR1)

GVM_MAKE_ID(TEXCOORD)
GVM_MAKE_ID(TEXCOORD0)
GVM_MAKE_ID(TEXCOORD1)
GVM_MAKE_ID(TEXCOORD2)

GVM_MAKE_ID(TEXCOORD3)
GVM_MAKE_ID(TEXCOORD4)
GVM_MAKE_ID(TEXCOORD5)
GVM_MAKE_ID(TEXCOORD6)
GVM_MAKE_ID(TEXCOORD7)

GVM_MAKE_ID(TANGENT)
GVM_MAKE_ID(BINORMAL)
GVM_MAKE_ID(TESSFACTOR)

// file ext
GVM_MAKE_ID(obj)
GVM_MAKE_ID(x)
GVM_MAKE_ID(dds)
GVM_MAKE_ID(fbx)
GVM_MAKE_ID(rfx)
GVM_MAKE_ID(3ds)
GVM_MAKE_ID(dae)
GVM_MAKE_ID(tga)
GVM_MAKE_ID(jpg)
GVM_MAKE_ID(png)

// animation name
GVM_MAKE_ID(Attack2H)
GVM_MAKE_ID(Attack2H1)
GVM_MAKE_ID(AttackOff)
GVM_MAKE_ID(Stand)
GVM_MAKE_ID(Parry2H)
GVM_MAKE_ID(Ready2H)
GVM_MAKE_ID(Special2H)
GVM_MAKE_ID(Walkbackwards)
GVM_MAKE_ID(AttackBow)
GVM_MAKE_ID(AttackOffPierce)
GVM_MAKE_ID(AttackRifle)
GVM_MAKE_ID(Dodge)
GVM_MAKE_ID(HoldBow)
GVM_MAKE_ID(HoldRifle)
GVM_MAKE_ID(LoadBow)
GVM_MAKE_ID(LoadRifle)
GVM_MAKE_ID(ReadyBow)
GVM_MAKE_ID(ReadyRifle)
GVM_MAKE_ID(Run)
GVM_MAKE_ID(ShuffleLeft)
GVM_MAKE_ID(ShuffleRight)
GVM_MAKE_ID(StealthStand)
GVM_MAKE_ID(StealthWalk)
GVM_MAKE_ID(Attack2HL)
GVM_MAKE_ID(Attack2HL1)
GVM_MAKE_ID(Attack2HL2)
GVM_MAKE_ID(Parry2HL)
GVM_MAKE_ID(Ready2HL)
GVM_MAKE_ID(CombatWound)
GVM_MAKE_ID(StandWound)
GVM_MAKE_ID(SwimBackwards)
GVM_MAKE_ID(SwimIdle)
GVM_MAKE_ID(Swim)
GVM_MAKE_ID(AttackUnarmed)
GVM_MAKE_ID(AttackUnarmed1)
GVM_MAKE_ID(AttackThrown)
GVM_MAKE_ID(ReadyThrown)
GVM_MAKE_ID(ReadyUnarmed)
GVM_MAKE_ID(Stand1)
GVM_MAKE_ID(ParryUnarmed)
GVM_MAKE_ID(AttackOff1)
GVM_MAKE_ID(Special1H)
GVM_MAKE_ID(Attack1H)
GVM_MAKE_ID(Attack1H1)
GVM_MAKE_ID(Knockdown)
GVM_MAKE_ID(Parry1H)
GVM_MAKE_ID(Ready1H)
GVM_MAKE_ID(DragonStomp)
GVM_MAKE_ID(SpellCastDirected)
GVM_MAKE_ID(ChannelCastDirected)
GVM_MAKE_ID(CombatCritical)
GVM_MAKE_ID(Death)
GVM_MAKE_ID(EmoteSalute)
GVM_MAKE_ID(EmoteSaluteNoSheathe)
GVM_MAKE_ID(EmoteShout)
GVM_MAKE_ID(EmoteTalkQuestion)
GVM_MAKE_ID(ReadySpellDirected)
GVM_MAKE_ID(SwimLeft)
GVM_MAKE_ID(SwimRight)
GVM_MAKE_ID(Kick)
GVM_MAKE_ID(Stun)
GVM_MAKE_ID(EmoteStunNoSheathe)
GVM_MAKE_ID(Whirlwind)
GVM_MAKE_ID(EmoteApplaud)
GVM_MAKE_ID(EmoteBow)
GVM_MAKE_ID(EmoteCry)
GVM_MAKE_ID(EmotePoint)
GVM_MAKE_ID(EmoteRoar)
GVM_MAKE_ID(EmoteShy)
GVM_MAKE_ID(Fall)
GVM_MAKE_ID(FishingCast)
GVM_MAKE_ID(FishingLoop)
GVM_MAKE_ID(HandsClosed)
GVM_MAKE_ID(HipSheath)
GVM_MAKE_ID(Jump)
GVM_MAKE_ID(JumpEnd)
GVM_MAKE_ID(JumpLandRun)
GVM_MAKE_ID(Loot)
GVM_MAKE_ID(Sheath)
GVM_MAKE_ID(SitChairLow)
GVM_MAKE_ID(SitChairMed)
GVM_MAKE_ID(SitGround)
GVM_MAKE_ID(SitGroundDown)
GVM_MAKE_ID(SitGroundUp)
GVM_MAKE_ID(Stop)
GVM_MAKE_ID(EmoteTalkExclamation)
GVM_MAKE_ID(EmoteWave)
GVM_MAKE_ID(EmoteWork)
GVM_MAKE_ID(EmoteWorkNoSheathe)
GVM_MAKE_ID(EmoteFlex)
GVM_MAKE_ID(EmoteKiss)
GVM_MAKE_ID(EmoteTalk)
GVM_MAKE_ID(ChannelCastOmni)
GVM_MAKE_ID(Drown)
GVM_MAKE_ID(Drowned)
GVM_MAKE_ID(EmoteBeg)
GVM_MAKE_ID(EmoteEat)
GVM_MAKE_ID(EmoteEatNoSheathe)
GVM_MAKE_ID(EmoteLaugh)
GVM_MAKE_ID(EmoteRude)
GVM_MAKE_ID(ReadySpellOmni)
GVM_MAKE_ID(SpellCastOmni)
GVM_MAKE_ID(Sprint)
GVM_MAKE_ID(UseStandingEnd)
GVM_MAKE_ID(UseStandingLoop)
GVM_MAKE_ID(EmoteUseStanding)
GVM_MAKE_ID(EmoteUseStandingNoSheathe)
GVM_MAKE_ID(UseStandingStart)
GVM_MAKE_ID(JumpStart)
GVM_MAKE_ID(JumpStart1)
GVM_MAKE_ID(EmoteCheer)
GVM_MAKE_ID(EmoteChicken)
GVM_MAKE_ID(EmoteKneel)
GVM_MAKE_ID(EmoteNo)
GVM_MAKE_ID(EmoteTrain)
GVM_MAKE_ID(EmoteYes)
GVM_MAKE_ID(KneelEnd)
GVM_MAKE_ID(SpellKneelEnd)
GVM_MAKE_ID(KneelLoop)
GVM_MAKE_ID(SpellKneelLoop)
GVM_MAKE_ID(KneelStart)
GVM_MAKE_ID(SpellKneelStart)
GVM_MAKE_ID(ShieldBash)
GVM_MAKE_ID(ShieldBlock)
GVM_MAKE_ID(Sleep)
GVM_MAKE_ID(SleepDown)
GVM_MAKE_ID(SpellSleepDown)
GVM_MAKE_ID(SleepUp)
GVM_MAKE_ID(Mount)
GVM_MAKE_ID(Mount1)
GVM_MAKE_ID(EmoteDance)
GVM_MAKE_ID(EmoteTalk1)
GVM_MAKE_ID(HoldThrown)
GVM_MAKE_ID(SitChairHigh)
GVM_MAKE_ID(SpecialUnarmed)
GVM_MAKE_ID(EmoteDance1)
GVM_MAKE_ID(EmoteDance2)
GVM_MAKE_ID(Attack1HPierce)
GVM_MAKE_ID(BattleRoar)
GVM_MAKE_ID(Walk)
GVM_MAKE_ID(Stand2)
GVM_MAKE_ID(Hover)
GVM_MAKE_ID(StealthRun)
GVM_MAKE_ID(Mutilate)
GVM_MAKE_ID(Cower)
GVM_MAKE_ID(CustomSpell01)
GVM_MAKE_ID(CustomSpell02)
GVM_MAKE_ID(Strangulate)
GVM_MAKE_ID(HoldJoust)
GVM_MAKE_ID(LoadJoust)
GVM_MAKE_ID(ReadyJoust)
GVM_MAKE_ID(AttackJoust)

#undef GVM_DCL_CHANNEL
#define GVM_DCL_CHANNEL(x) GVM_MAKE_ID(x)
#include "gv_event_channels.h"