GVM_DOM_ELEMENT(gv_ani_play_info)
GVM_DOM_ATTRIB(gv_float, m_current_time)
GVM_DOM_ATTRIB(gv_float, m_end_time)
GVM_DOM_ATTRIB(gv_float, m_blending_time)
GVM_DOM_ATTRIB(gv_bool, m_loop)
GVM_DOM_ATTRIB(gv_bool, m_blending_start)
GVM_DOM_ATTRIB(gvt_ref_ptr< gv_ani_sequence >, m_ani_sequence)
GVM_DOM_ATTRIB(gvt_ref_ptr< gv_com_tasklet >, m_task_on_ani_stop)
GVM_DOM_ATTRIB(gvt_ptr< gv_ani_play_info >, m_next)
GVM_DOM_END_E
