REG_UNIT_TEST(unit_test_reflection)
REG_UNIT_TEST(unit_test_sandbox)
REG_UNIT_TEST(unit_test_entity)
REG_UNIT_TEST(unit_test_fixed_point)
REG_UNIT_TEST(unit_test_processor)
REG_UNIT_TEST(unit_test_save_load)

REG_UNIT_TEST(unit_test_3d_init)
REG_UNIT_TEST(unit_test_load_x_file)
REG_UNIT_TEST(unit_test_importer_exporter)
REG_UNIT_TEST(unit_test_importer_exporter_3ds)
REG_UNIT_TEST(unit_test_importer_exporter_fbx)
REG_UNIT_TEST(unit_test_importer_exporter_rfx)
REG_UNIT_TEST(unit_test_display_animation)

REG_UNIT_TEST(unit_test_rfx_view)
REG_UNIT_TEST(unit_test_3d_lobby)
REG_UNIT_TEST(unit_test_roam_terrain)
REG_UNIT_TEST(unit_test_ai_control)
REG_UNIT_TEST(unit_test_job_queue)
REG_UNIT_TEST(unit_test_image)
REG_UNIT_TEST(unit_test_image_process)
REG_UNIT_TEST(unit_test_game_engine)
REG_UNIT_TEST(unit_test_game_engine_async_load)
REG_UNIT_TEST(unit_test_world_2d)
REG_UNIT_TEST(unit_test_world_3d)
REG_UNIT_TEST(unit_test_rts)

REG_UNIT_TEST(unit_test_network_chat)
REG_UNIT_TEST(unit_test_network_send_command)
REG_UNIT_TEST(unit_test_network_replica)

REG_UNIT_TEST(unit_test_network_lobby_with_replica)
REG_UNIT_TEST(unit_test_network_lobby_mmo)
REG_UNIT_TEST(unit_test_network_login)
#if WIN32 && GV_WITH_DATABASE
REG_UNIT_TEST(unit_test_network_database)
#endif
#if WITH_CEGUI
REG_UNIT_TEST(unit_test_ui_cegui)
#endif

REG_UNIT_TEST(tool_binarize)
REG_UNIT_TEST(tool_morph_texture_builder)
