GVM_DOM_ELEMENT(RmEffectWorkspace)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ACTIVE_EFFECT)
GVM_DOM_ATTRIB(gv_string, VALIDATION_STRING)
GVM_DOM_ATTRIB(gv_string, XML_VERSION)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmEffectGroup)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmDirectXEffect)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ACTIVE_CAMERA)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmOpenGLEffect)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ACTIVE_CAMERA)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmPass)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PASS_INDEX)
GVM_DOM_ATTRIB(gv_string, ENABLED)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmGLPass)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PASS_INDEX)
GVM_DOM_ATTRIB(gv_string, ENABLED)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmShader)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PIXEL_SHADER)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmHLSLShader)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PIXEL_SHADER)
GVM_DOM_ATTRIB(gv_string, TARGET)
GVM_DOM_ATTRIB(gv_string, ENTRY_POINT)
GVM_DOM_ATTRIB(gv_string, COMPILER_FLAGS)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmGLShader)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PIXEL_SHADER)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmShaderConstant)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_int, REGISTER)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmSampler)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_int, REGISTER)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmTextureObject)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_int, STATE_INDEX)
GVM_DOM_ATTRIB(gv_string, VERTEX_TEXTURE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmLightObject)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, INDEX)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmMaterialObject)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, INDEX)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmRenderStateBlock)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmState)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_int, STATE)
GVM_DOM_ATTRIB(gv_int, VALUE)
GVM_DOM_ATTRIB(gv_string, USAGE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmStreamMap)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmStream)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, STRIDE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmStreamChannel)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, DATA_SIZE)
GVM_DOM_ATTRIB(gv_int, DATA_TYPE)
GVM_DOM_ATTRIB(gv_string, REGISTER)
GVM_DOM_ATTRIB(gv_int, USAGE)
GVM_DOM_ATTRIB(gv_int, USAGE_INDEX)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmModelData)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, FILE_NAME)
GVM_DOM_ATTRIB(gv_string, ORIENTATION)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmTextureReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmLightReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmMaterialReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmModelReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmStreamMapReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmRenderableTexture)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, FILE_NAME)
GVM_DOM_ATTRIB(gv_string, ORIGIN)
GVM_DOM_ATTRIB(gv_string, WIDTH)
GVM_DOM_ATTRIB(gv_string, HEIGHT)
GVM_DOM_ATTRIB(gv_string, FORMAT)
GVM_DOM_ATTRIB(gv_string, USE_VIEWPORT_DIMENSIONS)
GVM_DOM_ATTRIB(gv_string, GENERATE_MIPMAPS)
GVM_DOM_ATTRIB(gv_string, WIDTH_RATIO)
GVM_DOM_ATTRIB(gv_string, HEIGHT_RATIO)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmRenderTarget)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, INDEX)
GVM_DOM_ATTRIB(gv_string, RENDER_TO_SCREEN)
GVM_DOM_ATTRIB(gv_string, COLOR_CLEAR)
GVM_DOM_ATTRIB(gv_string, DEPTH_CLEAR)
GVM_DOM_ATTRIB(gv_string, CLEAR_COLOR_VALUE)
GVM_DOM_ATTRIB(gv_string, DEPTH_CLEAR_VALUE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmBooleanVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, VALUE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmFloatVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, VALUE)
GVM_DOM_ATTRIB(gv_string, MIN)
GVM_DOM_ATTRIB(gv_string, MAX)
GVM_DOM_ATTRIB(gv_string, CLAMP)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmVectorVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_float, VALUE_0)
GVM_DOM_ATTRIB(gv_float, VALUE_1)
GVM_DOM_ATTRIB(gv_float, VALUE_2)
GVM_DOM_ATTRIB(gv_float, VALUE_3)
GVM_DOM_ATTRIB(gv_string, MIN)
GVM_DOM_ATTRIB(gv_string, MAX)
GVM_DOM_ATTRIB(gv_string, CLAMP)
GVM_DOM_ATTRIB(gv_string, NORMALIZE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmMatrixVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_float, VALUE_0)
GVM_DOM_ATTRIB(gv_float, VALUE_1)
GVM_DOM_ATTRIB(gv_float, VALUE_2)
GVM_DOM_ATTRIB(gv_float, VALUE_3)
GVM_DOM_ATTRIB(gv_float, VALUE_4)
GVM_DOM_ATTRIB(gv_float, VALUE_5)
GVM_DOM_ATTRIB(gv_float, VALUE_6)
GVM_DOM_ATTRIB(gv_float, VALUE_7)
GVM_DOM_ATTRIB(gv_float, VALUE_8)
GVM_DOM_ATTRIB(gv_float, VALUE_9)
GVM_DOM_ATTRIB(gv_float, VALUE_10)
GVM_DOM_ATTRIB(gv_float, VALUE_11)
GVM_DOM_ATTRIB(gv_float, VALUE_12)
GVM_DOM_ATTRIB(gv_float, VALUE_13)
GVM_DOM_ATTRIB(gv_float, VALUE_14)
GVM_DOM_ATTRIB(gv_float, VALUE_15)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmDynamicVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, VARIABLE_TYPE)
GVM_DOM_ATTRIB(gv_int, ROWS)
GVM_DOM_ATTRIB(gv_int, COLUMNS)
GVM_DOM_ATTRIB(gv_string, FIXED_SIZE)
GVM_DOM_ATTRIB(gv_string, MIN)
GVM_DOM_ATTRIB(gv_string, MAX)
GVM_DOM_ATTRIB(gv_string, CLAMP)
GVM_DOM_ATTRIB(gv_string, NORMALIZE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmDynamicVariableValue)
GVM_DOM_ATTRIB(gv_int, ROW_INDEX)
GVM_DOM_ATTRIB(gv_int, COLUMN_INDEX)
GVM_DOM_ATTRIB(gv_string, VALUE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmColorVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_float, VALUE_0)
GVM_DOM_ATTRIB(gv_float, VALUE_1)
GVM_DOM_ATTRIB(gv_float, VALUE_2)
GVM_DOM_ATTRIB(gv_float, VALUE_3)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmIntegerVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, VALUE)
GVM_DOM_ATTRIB(gv_string, MIN)
GVM_DOM_ATTRIB(gv_string, MAX)
GVM_DOM_ATTRIB(gv_string, CLAMP)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmStringVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_END_E

GVM_DOM_ELEMENT(Rm2DTextureVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, FILE_NAME)
GVM_DOM_ATTRIB(gv_string, ORIGIN)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmCubemapVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, FILE_NAME)
GVM_DOM_ATTRIB(gv_string, ORIGIN)
GVM_DOM_END_E

GVM_DOM_ELEMENT(Rm3DTextureVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, FILE_NAME)
GVM_DOM_ATTRIB(gv_string, ORIGIN)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmLightVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, LIGHT_ENABLED)
GVM_DOM_ATTRIB(gv_string, LIGHT_TYPE)
GVM_DOM_ATTRIB(gv_string, AMBIENT_0)
GVM_DOM_ATTRIB(gv_string, AMBIENT_1)
GVM_DOM_ATTRIB(gv_string, AMBIENT_2)
GVM_DOM_ATTRIB(gv_string, AMBIENT_3)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_0)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_1)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_2)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_3)
GVM_DOM_ATTRIB(gv_string, SPECULAR_0)
GVM_DOM_ATTRIB(gv_string, SPECULAR_1)
GVM_DOM_ATTRIB(gv_string, SPECULAR_2)
GVM_DOM_ATTRIB(gv_string, SPECULAR_3)
GVM_DOM_ATTRIB(gv_string, POSITION_0)
GVM_DOM_ATTRIB(gv_string, POSITION_1)
GVM_DOM_ATTRIB(gv_string, POSITION_2)
GVM_DOM_ATTRIB(gv_string, DIRECTION_0)
GVM_DOM_ATTRIB(gv_string, DIRECTION_1)
GVM_DOM_ATTRIB(gv_string, DIRECTION_2)
GVM_DOM_ATTRIB(gv_string, ATTENUATION_0)
GVM_DOM_ATTRIB(gv_string, ATTENUATION_1)
GVM_DOM_ATTRIB(gv_string, ATTENUATION_2)
GVM_DOM_ATTRIB(gv_string, SPOTLIGHT_THETA)
GVM_DOM_ATTRIB(gv_string, SPOTLIGHT_PHI)
GVM_DOM_ATTRIB(gv_string, RANGE)
GVM_DOM_ATTRIB(gv_string, FALLOFF)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmMaterialVariable)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, ARTIST_EDITABLE)
GVM_DOM_ATTRIB(gv_string, VARIABLE_SEMANTIC)
GVM_DOM_ATTRIB(gv_string, AMBIENT_0)
GVM_DOM_ATTRIB(gv_string, AMBIENT_1)
GVM_DOM_ATTRIB(gv_string, AMBIENT_2)
GVM_DOM_ATTRIB(gv_string, AMBIENT_3)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_0)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_1)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_2)
GVM_DOM_ATTRIB(gv_string, DIFFUSE_3)
GVM_DOM_ATTRIB(gv_string, SPECULAR_0)
GVM_DOM_ATTRIB(gv_string, SPECULAR_1)
GVM_DOM_ATTRIB(gv_string, SPECULAR_2)
GVM_DOM_ATTRIB(gv_string, SPECULAR_3)
GVM_DOM_ATTRIB(gv_string, EMISSIVE_0)
GVM_DOM_ATTRIB(gv_string, EMISSIVE_1)
GVM_DOM_ATTRIB(gv_string, EMISSIVE_2)
GVM_DOM_ATTRIB(gv_string, EMISSIVE_3)
GVM_DOM_ATTRIB(gv_string, SPECULAR_POWER)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmRegistryBranch)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, XML_VERSION)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmPlugInData)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, PLUGIN_GUID)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmClipboardNode)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, XML_VERSION)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmCamera)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_float, CAMERA_POSITION_X)
GVM_DOM_ATTRIB(gv_float, CAMERA_POSITION_Y)
GVM_DOM_ATTRIB(gv_float, CAMERA_POSITION_Z)
GVM_DOM_ATTRIB(gv_float, LOOK_AT_VECTOR_X)
GVM_DOM_ATTRIB(gv_float, LOOK_AT_VECTOR_Y)
GVM_DOM_ATTRIB(gv_float, LOOK_AT_VECTOR_Z)
GVM_DOM_ATTRIB(gv_float, UP_VECTOR_X)
GVM_DOM_ATTRIB(gv_float, UP_VECTOR_Y)
GVM_DOM_ATTRIB(gv_float, UP_VECTOR_Z)
GVM_DOM_ATTRIB(gv_float, FOV)
GVM_DOM_ATTRIB(gv_float, NEAR_CLIP_PLANE)
GVM_DOM_ATTRIB(gv_float, FAR_CLIP_PLANE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmCameraReference)
GVM_DOM_ATTRIB(gv_string, NAME)
GVM_DOM_ATTRIB(gv_string, API)
GVM_DOM_ATTRIB(gv_string, USE_ACTIVE_CAMERA)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmShaderCode)
GVM_DOM_ATTRIB(gv_string, TYPE)
GVM_DOM_END_E

GVM_DOM_ELEMENT(RmTextDataBlock)
GVM_DOM_ATTRIB(gv_string, TYPE)
GVM_DOM_END_E
