//=================================================================================>
#if defined(GVM_DCL_PIXEL_FORMAT_GET_STRING)
#undef GVM_DCL_PIXEL_FORMAT
#define GVM_DCL_PIXEL_FORMAT(type) \
	case gve_pixel_##type:         \
		return #type;
#elif defined(GVM_DCL_PIXEL_FORMAT_FROM_STRING)
#undef GVM_DCL_PIXEL_FORMAT
#define GVM_DCL_PIXEL_FORMAT(type) \
	if (s == #type)                \
		return gve_pixel_##type;
#elif defined(GVM_DCL_PIXEL_FORMAT_MAKE_ENUM)
#undef GVM_DCL_PIXEL_FORMAT
#define GVM_DCL_PIXEL_FORMAT(type) gve_pixel_##type,
#elif defined(GVM_DCL_PIXEL_FORMAT_CHANGE_PREFIX)
#undef GVM_DCL_PIXEL_FORMAT
#define GVM_DCL_PIXEL_FORMAT(type) \
	case gve_pixel_##type:         \
		return GV_MACRO_CONCATE2(GVM_PIXEL_PREFIX, type);
#else
#error
#endif
//=================================================================================>

GVM_DCL_PIXEL_FORMAT(R8G8B8)
GVM_DCL_PIXEL_FORMAT(A8R8G8B8)
GVM_DCL_PIXEL_FORMAT(X8R8G8B8)
GVM_DCL_PIXEL_FORMAT(R5G6B5)
GVM_DCL_PIXEL_FORMAT(X1R5G5B5)
GVM_DCL_PIXEL_FORMAT(A1R5G5B5)
GVM_DCL_PIXEL_FORMAT(A4R4G4B4)
GVM_DCL_PIXEL_FORMAT(R3G3B2)
GVM_DCL_PIXEL_FORMAT(A8)
GVM_DCL_PIXEL_FORMAT(A8R3G3B2)
GVM_DCL_PIXEL_FORMAT(X4R4G4B4)
GVM_DCL_PIXEL_FORMAT(A2B10G10R10)
GVM_DCL_PIXEL_FORMAT(A8B8G8R8)
GVM_DCL_PIXEL_FORMAT(X8B8G8R8)
GVM_DCL_PIXEL_FORMAT(G16R16)
GVM_DCL_PIXEL_FORMAT(A2R10G10B10)
GVM_DCL_PIXEL_FORMAT(A16B16G16R16)
GVM_DCL_PIXEL_FORMAT(A8P8)
GVM_DCL_PIXEL_FORMAT(P8)
GVM_DCL_PIXEL_FORMAT(L8)
GVM_DCL_PIXEL_FORMAT(A8L8)
GVM_DCL_PIXEL_FORMAT(A4L4)
GVM_DCL_PIXEL_FORMAT(V8U8)
GVM_DCL_PIXEL_FORMAT(L6V5U5)
GVM_DCL_PIXEL_FORMAT(X8L8V8U8)
GVM_DCL_PIXEL_FORMAT(Q8W8V8U8)
GVM_DCL_PIXEL_FORMAT(V16U16)
GVM_DCL_PIXEL_FORMAT(A2W10V10U10)
GVM_DCL_PIXEL_FORMAT(UYVY)
GVM_DCL_PIXEL_FORMAT(R8G8_B8G8)
GVM_DCL_PIXEL_FORMAT(YUY2)
GVM_DCL_PIXEL_FORMAT(G8R8_G8B8)
GVM_DCL_PIXEL_FORMAT(DXT1)
GVM_DCL_PIXEL_FORMAT(DXT2)
GVM_DCL_PIXEL_FORMAT(DXT3)
GVM_DCL_PIXEL_FORMAT(DXT4)
GVM_DCL_PIXEL_FORMAT(DXT5)
GVM_DCL_PIXEL_FORMAT(D16_LOCKABLE)
GVM_DCL_PIXEL_FORMAT(D32)
GVM_DCL_PIXEL_FORMAT(D15S1)
GVM_DCL_PIXEL_FORMAT(D24S8)
GVM_DCL_PIXEL_FORMAT(D24X8)
GVM_DCL_PIXEL_FORMAT(D24X4S4)
GVM_DCL_PIXEL_FORMAT(D16)
GVM_DCL_PIXEL_FORMAT(D32F_LOCKABLE)
GVM_DCL_PIXEL_FORMAT(D24FS8)
GVM_DCL_PIXEL_FORMAT(L16)
GVM_DCL_PIXEL_FORMAT(VERTEXDATA)
GVM_DCL_PIXEL_FORMAT(INDEX16)
GVM_DCL_PIXEL_FORMAT(INDEX32)
GVM_DCL_PIXEL_FORMAT(Q16W16V16U16)
GVM_DCL_PIXEL_FORMAT(MULTI2_ARGB8)
GVM_DCL_PIXEL_FORMAT(R16F)
GVM_DCL_PIXEL_FORMAT(G16R16F)
GVM_DCL_PIXEL_FORMAT(A16B16G16R16F)
GVM_DCL_PIXEL_FORMAT(R32F)
GVM_DCL_PIXEL_FORMAT(G32R32F)
GVM_DCL_PIXEL_FORMAT(A32B32G32R32F)
GVM_DCL_PIXEL_FORMAT(CxV8U8)

//=================================================================================>
#undef GVM_DCL_PIXEL_FORMAT
#undef GVM_DCL_PIXEL_FORMAT_GET_STRING
#undef GVM_DCL_PIXEL_FORMAT_FROM_STRING
#undef GVM_DCL_PIXEL_FORMAT_MAKE_ENUM
#undef GVM_DCL_PIXEL_FORMAT_CHANGE_PREFIX
